#ifndef CONSTANTS
#define CONSTANTS

#define END_OF_LIST -2
#define ALL -1
#define FALSE 0
#define TRUE 1
#define MAX_NUM_DIM 5
#define AVAIL_NUM_INDEXES 10

#define DIM_SIZE_MISMATCH 2
#define NOT_ENOUGH_INDEXES 3
#define OUTSIDE_RANGE 4
#define STRIDES_SIZE_MISMATCH 5
#define SHAPE_SIZE_MISMATCH 6
#define EXCEED_MAX_NUM_DIM 7
#define IDX_FMT_DIM_MISMATCH 8
#define COMMON_IDX_SIZE_MISMATCH 9
#define IDX_DIM_MISMATCH 10
#define DIM_TOO_HIGH 11

#endif
